name: deploy
on:
  push:
    branches:
      - "main"
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  release:
    types: [published]

jobs:
  build-and-deploy:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_API_URL: "https://mybmwreward.com"
          envkey_REACT_APP_SOCKET_URL: "https://mybmwreward.com"
          file_name: .env

      # - run: yarn install
      # - run: yarn build
      - run: echo ${{ secrets.PROD_USERKEY }}

      # - name: Run script
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.PROD_HOST }}
      #     username: ${{ secrets.PROD_USERNAME }}
      #     key: ${{ secrets.PROD_USERKEY }}
      #     port: 22
      #     script: export NODE_ENV=production; cd ${{ secrets.PROD_TARGET_DIR }} && npm i && pm2 restart all

      # - name: Deploy via ssh
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.PROD_HOST }}
      #     username: ${{ secrets.PROD_USERNAME }}
      #     key: ${{ secrets.PROD_USERKEY }}
      #     source: "./build"
      #     target: ${{ secrets.PROD_DEPLOY_PATH }}
